apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "your-app.fullname" . }}-servicemonitor
  labels:
    release: {{ .Release.Name }}
    app: {{ include "your-app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "your-app.name" . }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s