apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "test-app.fullname" . }}-servicemonitor
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "test-app.labels" . | nindent 4 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s